apiVersion: v1
kind: Secret
metadata:
  name: demo-secrets
type: Opaque
data:
  PGUSER: ZGJ1c2Vy
  PGHOST: ZGF0YWJhc2Uuc2VydmVyLmNvbQ==
  PGPASSWORD: c2VjcmV0cGFzc3dvcmQ=
  PGDATABASE: bXlkYg==
  PGPORT: MzIxMQ==

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-deployment
  labels:
    app: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: demo
        image: demo:latest
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
        envFrom:
        - secretRef:
            name: demo-secrets